apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-project
  labels:
    app: nodejs-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-project
  template:
    metadata:
      labels:
        app: nodejs-project
    spec:
      containers:
      - name: nodejs-project
        image: nocnex/nodejs-project:latest
      env:
        - name: MONGO_URL  # Your app expects this variable
          value: "mongodb://admin:password@mongodb:27017/mydatabase"

        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
