apiVersion: v1
kind: Service
metadata:
  name: nodejs-project
spec:
  selector:
    app: nodejs-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
